[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 999_999

remappings = ["hiero-contracts/=src/"]

[rpc_endpoints]
hedera_mainnet = "https://mainnet.hashio.io/api"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
